apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: gitops  # Change the namespace to gitops
  labels:
    app: kubernetes-dashboard
spec:
  selector:
    app: kubernetes-dashboard
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
